---
deployment:
  tasks:
    - export DEPLOYPATH=/home/valerymassageser/public_html/
    - /bin/echo "Deploying to ${DEPLOYPATH}"
    - /bin/mkdir -p "${DEPLOYPATH}"
    - /bin/cp -R index.html index-en.html index-de.html privacy.html cookie.html img "${DEPLOYPATH}"
